### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by copejon** [yard-turkey/lib-bucket-provisioner#46]
An ever expanding list of things that should (probably) be done

- [x] refactor unexported methods into help funcs

- [x] organize help funcs! (util/ should not be a catchall)

- [x] refactor funcs to `internal/` subdir of the controller

- [x] API validation / webhooks

- [x] update unit tests - the crunch we've been under means a lot of untested funcs and stale tests

- [x] Add ACLs field in OBC (e.g. PublicReadWrite, PublicRead, etc)

- [x] Add Policy field in OBC (e.g. RO, WO, RW permissions for generated key)

- [x] API change: add API to request additional key pairs to dynamic bucket

- [ ] ~leader election to enable fail over in deployment~

- [ ] Prometheus integration

- [ ] event logging in OBC

- [ ] CI linters/vetters should be finalized and build failure should be defined

- [x] move developer how-to doc into lib repo (from examples repo)

- [ ] review design doc for adherence to overall vision (does it include the above features?)

- [ ] code walk - before we can hand this off, we should give deep cleaning (reduce redundancy, detangle spaghetti code) 

- [ ] enable custom loggers

- [ ] rework provisioner constructor.  field additions/deletions force a change to the parameter list.  we should find a more stable strategy to allow for structural changes that don't break NewProvisioner() callers.  One alternative is a set of method calls that can be chained together arbitrarily to set individual options.  Another is a variadic parameter list of type setter functions, detailed [here](https://github.com/tmrts/go-patterns/blob/master/idiom/functional-options.md)

- [ ] logging clean up and configurable verbosity levels for info and debug
